### ISSUE TITLE
not worknig

### ISSUE THREAD

**Issue by mayersgamer** [Franc1sco/CS2-AntiTeamFlash#3]
[Client]   [#9:LOADED]: "Anti Team Flash" (0.0.1) by Franc1sco Franug

my teamates are still getting flashed in casual server

**Comment by Franc1sco** [comment]
Try this -> https://github.com/Franc1sco/CS2-AntiTeamFlash/tree/dev release here https://github.com/Franc1sco/CS2-AntiTeamFlash/tree/dev/release
